apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller-sa
      containers:
      - name: dummysite-controller
        image: irmindev/dummysite:1.4
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: dummysite-svc
spec:
  type: LoadBalancer # This should be the only unfamiliar part
  selector:
    app: dummysite-controller
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5672