apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      volumes: # Define volume
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: api-server
          image: irmindev/api-server:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files
          ports:
            - containerPort: 8080
