apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:pbEm2vs49yDPCkZWczQQEDMXl3b5FVla,iv:avyaNjsGDnJTfFPKgUCRiEMjxySayDamfzc+/kPC80E=,tag:8lT/9+bZ9mJJ5Kxnx0q2WQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:FRyjGA4VrMf2WLQ/,iv:p/BeI16N/gCQ/vED6KfQybA6QRz7BdcQg6o2t5wnytY=,tag:Phmtx6uK81s721Ww2cw7Cw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:OjFdUafdVgyWUM7m,iv:pLtvbrgqxNV8AebKm6C31iP+9kgyFdw1XJlOMLXK28Q=,tag:KhI39rdi9WZwL/IKQi8gFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x630wtp8l8zl75rx2zetv2k6kjnwqwcv66uj73cdpnvm943535zsgva6eh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNjFqVHNlaXJIWGIza0J6
            VnRlaUt6RFNyT0x5WWppTVJweDd2UEdPd2k0CnJXV3htaUFNRFVMdnpmZmxYTTl0
            SjYrcm1sRUhNNUUwMjYwQ2s5VmlIYlEKLS0tIFJDdUZJUmtmOHIyOWQ0bmVVWjdo
            NytFOFRabytLeldHLzk3eWdXVlg1ZDQKwnrG15OtSa8gehrHdZK3FDrMrED4MFe1
            DlA54vuZwxGnUTwfj2qqtgk8e9F0RNypY7CXHMnGvfYHyd3b/d+rSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T04:30:48Z"
    mac: ENC[AES256_GCM,data:edPX7P/pMEfUCDMnlimyOzKo2Pn67GNypQSK5AHEnun5I+2U7TwdeAaQHZAC9dbWULQPCozJvLoUcFoBa9GODiofdCvuUFR8xmvUqonpm61wTQc53CnCry2L0NB/e0zIRkztO2vxBw6Fxt6hiaoIIujy65Fk9nYutLoW9RA/m00=,iv:W6nr3fvkFbgRWAqFyjc7LaFl04fCny6zqwbST6sTqmI=,tag:1RaJhhMOG/dp7FmjVzo2EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
