apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: irmindev/exercise-1-1:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: PING_PONG_URL
              value: "http://ping-pong-svc.default.svc.cluster.local:80"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-config
                  key: MESSAGE
          volumeMounts:
            - name: information
              mountPath: /etc/config
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
                path: /
                port: 3000
          readinessProbe:
              httpGet:
                  path: /
                  port: 3000
              initialDelaySeconds: 30
              periodSeconds: 10
              failureThreshold: 3
      volumes:
        - name: information
          configMap:
            name: log-config


