services:
  api-server:
    image: api-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./mvnw:/usr/src/app/mvnw
      - ./.mvn:/usr/src/app/.mvn
      - ./pom.xml:/usr/src/app/pom.xml
    environment:
      - PORT=8080
    container_name: api-server