apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: irmindev/todo-app
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: BACKEND_URL
              value: "http://todo-backend-svc:3456"
          ports:
            - containerPort: 8080
